### ISSUE TITLE
Why not have transparency?

### ISSUE THREAD

**Issue by Rotfuchs-von-Vulpes** [stonkpunk/my-npm-modules#1]
I tried to use this lib and it worked, but it didn't have the transparent background like the original image.

**Comment by Antix-Development** [comment]
If you modify the `placePixel` function you can get transparency...
````
    // expandedArr[++o] = 255; << replace this with the following line
    (((rgb[0] << 16) + (rgb[1] << 8) + rgb[2]) === 0xff00ff) ? expandedArr[++o] = 0 : expandedArr[++o] = 255;
````
You'll need to change the `0xff00ff` to the hex value of what flat color you want transparent pixels to be.

Of course this doesn't work with any anti-aliasing that your image might have, but you can achieve some transparency at least.

**Comment by Rotfuchs-von-Vulpes** [comment]
okej, that seems to be good enough :)
